// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	comment "sosmedapps/features/comment"

	mock "github.com/stretchr/testify/mock"
)

// CommentService is an autogenerated mock type for the CommentService type
type CommentService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: token, commentID
func (_m *CommentService) Delete(token interface{}, commentID uint) error {
	ret := _m.Called(token, commentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint) error); ok {
		r0 = rf(token, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCom provides a mock function with given fields:
func (_m *CommentService) GetCom() ([]comment.Core, error) {
	ret := _m.Called()

	var r0 []comment.Core
	if rf, ok := ret.Get(0).(func() []comment.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]comment.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewComment provides a mock function with given fields: token, contentID, NewComment
func (_m *CommentService) NewComment(token interface{}, contentID uint, NewComment string) (comment.Core, error) {
	ret := _m.Called(token, contentID, NewComment)

	var r0 comment.Core
	if rf, ok := ret.Get(0).(func(interface{}, uint, string) comment.Core); ok {
		r0 = rf(token, contentID, NewComment)
	} else {
		r0 = ret.Get(0).(comment.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, uint, string) error); ok {
		r1 = rf(token, contentID, NewComment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCommentService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommentService creates a new instance of CommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommentService(t mockConstructorTestingTNewCommentService) *CommentService {
	mock := &CommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
